name: Vérification

on:
  pull_request:
    branches:
      main
  workflow_dispatch:

jobs:
  Compilation:
    runs-on: ubuntu-latest
    environment: Vérification
    
    steps:
      - name: Compile project
        run: dotnet build /warnaserror
